apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/part-of: oficina-mecanica-dgcar
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "oficina"
  SPRING_DATASOURCE_PASSWORD: "troque-esta-senha"
  JWT_SECRET: "troque-esta-chave-com-no-minimo-32-caracteres"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
