apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/part-of: oficina-mecanica-dgcar
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: oficina-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
